config/routes.rb
Rails.application.routes.draw do
  resources :crews
  resources :concerts
  resources :bands

  root "bands#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    has_many :concerts, dependent: :destroy
    has_many :crew, dependent: :destroy

    enum band_type: %i[band girl_band boy_band]

    def all_assistants
        self.concerts.sum(:assistants)
        #self.concerts.map {|concert| concert.assistants } .sum
    end

    def this_month_concerts
        self.concerts.where(date: (Date.today.beginning_of_month)..(Date.today)).size
    end

    def last_concert
        self.concerts.order(:date).last
    end

    def last_concert_date
        self.last_concert.date.strftime("%A %Y-%B-%d")
    end

    def most_popular_concert
        self.concerts.maximum(:assistants)
    end

    def longest_concert
        self.concerts.maximum(:duration)
    end
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :band
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :band
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: %i[ show edit update destroy ]
  before_action :set_band_type, only: %i[ new edit ]
 
  # GET /bands or /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to band_url(@band), notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to band_url(@band), notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    def set_band_type
      @band_type = Band.band_types.keys.map {|type|[type.humanize, type] } 
    end



    # Only allow a list of trusted parameters through.
    def band_params
      params.require(:band).permit(:name, :members, :first_show, :band_type)
    end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]
  before_action :set_bands, only: %i[new edit]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to concert_url(@concert), notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concert_url(@concert), notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    def set_bands
      @bands = Band.pluck(:name, :id)
    end 

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:date, :place, :assistants, :duration, :band_id)
    end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews or /crews.json
  def index
    @crews = Crew.all
  end

  # GET /crews/1 or /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews or /crews.json
  def create
    @crew = Crew.new(crew_params)

    respond_to do |format|
      if @crew.save
        format.html { redirect_to crew_url(@crew), notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1 or /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to crew_url(@crew), notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1 or /crews/1.json
  def destroy
    @crew.destroy

    respond_to do |format|
      format.html { redirect_to crews_url, notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:name, :instrument, :band_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/bands/_form.html.erb
<%= form_with(model: band) do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
        <% band.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :members %>
    <%= form.number_field :members %>
  </div>

  <div class="field">
    <%= form.label :first_show %>
    <%= form.date_select :first_show, start_year: 1995 %>
  </div>

  <div class="field">
    <%= form.label :band_type %>
    <%= form.select :band_type, @band_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Miembros</th>
      <th>Primer show</th>
      <th>Tipo de Banda</th>
      <th>Cantidad Conciertos</th>
      <th>Público Total</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= band.members %></td>
        <td><%= band.first_show %></td>
        <td><%= band.band_type.humanize %></td>
        <td><%= band.concerts.size %></td>
        <td><%= band.all_assistants %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Members:</strong>
  <%= @band.members %>
</p>

<p>
  <strong>First show:</strong>
  <%= @band.first_show %>
</p>

<p>
  <strong>Band type:</strong>
  <%= @band.band_type.humanize %>
</p>

<p>
  <strong>Conciertos de este mes:</strong>
  <%= @band.this_month_concerts %>
</p>

<p>
  <strong>Último Concierto :</strong>
  <%= @band.last_concert_date %>
</p>

<p>
  <strong>Concierto más Popular :</strong>
  <%= @band.most_popular_concert %>
</p>

<p>
  <strong>Concierto Más Largo :</strong>
  <%= @band.longest_concert %> mins
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, start_year: 1995%>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :assistants %>
    <%= form.number_field :assistants %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :band_id %>
    <%= form.select :band_id, @bands  %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Place</th>
      <th>Assistants</th>
      <th>Duration</th>
      <th>Band</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.date %></td>
        <td><%= concert.place %></td>
        <td><%= concert.assistants %></td>
        <td><%= concert.duration %></td>
        <td><%= concert.band_id %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @concert.date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @concert.place %>
</p>

<p>
  <strong>Assistants:</strong>
  <%= @concert.assistants %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @concert.duration %>
</p>

<p>
  <strong>Band:</strong>
  <%= @concert.band_id %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/crews/_form.html.erb
<%= form_with(model: crew) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
        <% crew.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :instrument %>
    <%= form.text_field :instrument %>
  </div>

  <div class="field">
    <%= form.label :band_id %>
    <%= form.text_field :band_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instrument</th>
      <th>Band</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= crew.instrument %></td>
        <td><%= crew.band_id %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_crew_path %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<p>
  <strong>Instrument:</strong>
  <%= @crew.instrument %>
</p>

<p>
  <strong>Band:</strong>
  <%= @crew.band_id %>
</p>

<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductoraEventosDos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>